version: "3"  
services:
  prometheus:
    image: prom/prometheus:latest
    ports:
    - 9090:9090
    volumes:
    - "./prometheus.yml:/etc/prometheus/prometheus.yml"
  app:
    container_name: app
    build: ./flask_api/.
    ports:
    - "5000:5000"
    volumes:
    - "./flask_api/app.py:/app.py"
