global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["172.24.55.140:9090"]
  - job_name: app
    static_configs:
      - targets: ["172.24.55.140:5000"]
